# Generated by Django 4.2.3 on 2023-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage1', models.TextField()),
                ('Stage2', models.TextField()),
                ('Stage3', models.TextField()),
                ('Stage4', models.TextField()),
                ('Stage5', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
