# Generated by Django 4.2.3 on 2023-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='bot_response',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='assumptions',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='classification',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='dataset',
            field=models.TextField(default='DEFAULT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='enhancement',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='error',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='execution',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='execution_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='filtering',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='final_response',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='formatted_response',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='generation',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='modifies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='recheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='regeneration',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sql',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sql_query',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_prompt',
            field=models.TextField(default='NA'),
        ),
    ]
