# Generated by Django 4.2.3 on 2023-07-28 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='logs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
