# Generated by Django 4.2.3 on 2023-07-28 13:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_logs_pub_date_logs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=chat.models.get_ist_time),
        ),
    ]
