# Generated by Django 4.2.3 on 2023-07-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
