# Generated by Django 4.2.3 on 2023-07-28 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField()),
                ('initial_response', models.TextField()),
                ('format_instructions', models.TextField()),
                ('better_prompt_template', models.TextField()),
                ('better_response', models.TextField()),
                ('html_response', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
