app = "proto2"
primary_region = "ams"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  CELERY_BROKER_URL = "redis://default:5bcce6315ccc45bdbfa832c9114e42f4@fly-proto2-redis.upstash.io"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app", "celery", "flower"]

[[services]]
  protocol = "tcp"
  internal_port = 5432
  processes = ["app", "celery"]

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

[[services]]
  protocol = "tcp"
  internal_port = 5555
  processes = ["flower"]

  [[services.ports]]
    port = 5555

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[processes]]
  name = "app"
  command = "gunicorn Proto2.wsgi:application --bind 0.0.0.0:8000 --workers=2"

[[processes]]
  name = "celery"
  command = "celery -A Proto2 worker --loglevel=info"

[[processes]]
  name = "flower"
  command = "bash scripts/flower.sh"
